### ISSUE TITLE
tela do admin não possui logout

### ISSUE THREAD

**Issue by vitorhcassol** [PDS-1-P05/2023_1_front-end#31]
Quando o usuário administrador realiza login no sistema ele deve ser capaz de fazer um logout quando for de sua vontade. Tal funcionalidade não foi implementada e fere princípios de UX do sistema.

![image](https://user-images.githubusercontent.com/80921175/234666683-7527a679-3972-418e-b8ee-969a88f02f6f.png)

Uma possível solução seria inserir um ícone que remetesse a tal função no canto mais a direita da Header do sistema.

**Comment by leticiayurie** [comment]
eu ia entregar, mas deu erro.
agora foi.
finalmente.
amém.

https://github.com/PDS-1-P05/2023_1_front-end/assets/88344321/7241a277-7e9b-45d2-ae9b-ac2aa935406c
