### ISSUE TITLE
Uso de http no ambiente de desenvolvimento

### ISSUE THREAD

**Issue by giovanavalli** [PDS-1-P05/2023_1_front-end#37]
Em geral, não é recomendável usar o protocolo HTTP para o desenvolvimento de aplicações modernas, pois ele é inseguro e não é eficiente o suficiente para lidar com as necessidades das aplicações atuais.

@vitorhcassol você poderia mudar o protocolo de http para https?

**Comment by leticiayurie** [comment]
Foi resolvido semana passada, mas esquecerem de fechar
