### ISSUE TITLE
Problema na Tela de Login

### ISSUE THREAD

**Issue by leticiayurie** [PDS-1-P05/2023_1_front-end#46]
Tentei acessar o login e, pasmem, me deparei com isso.
![image](https://github.com/PDS-1-P05/2023_1_front-end/assets/88344321/e5a42a49-5630-44a9-8bb5-1b764984daba)

@guilhermectprado ou @vitorhcassol vocês conseguem ver isso?

**Comment by guilhermectprado** [comment]
Já sabemos onde é o problema, já irei corrigir! :3

**Comment by guilhermectprado** [comment]
Já foi corrigido portante, fecharei a issue!
