### ISSUE TITLE
Erro de exportação de dados do gráfico quando há valores nulos

### ISSUE THREAD

**Issue by guilhermectprado** [PDS-1-P05/2023_1_front-end#53]
Um problema foi descoberto em torno de valores nulos sendo retornados do back-end, onde prejudica o ato de exportação dos dados do gráfico, pois não é possível exportar os dados em CSV se algum valor é nulo. E também vai ser necessário que seja criado uma validação pelo front-end para averiguar a existência de valores nulos no arquivo submetido, fazendo com que não seja permitido o envio do arquivo se houver algum campo nulo.

![image](https://github.com/PDS-1-P05/2023.1_back-end/assets/71979988/ee323d45-d8e8-4030-9ee7-31d2e1cd423a)

![image](https://github.com/PDS-1-P05/2023.1_back-end/assets/71979988/d6592126-a493-4e49-9217-75dfd9a2a6af)

**Comment by vitorhcassol** [comment]
Issue corrigida!
