### ISSUE TITLE
Gerar gráfico sem município selecionado

### ISSUE THREAD

**Issue by vitorhcassol** [PDS-1-P05/2023_1_front-end#54]
De acordo com o Caso de Teste 25 da H001, quando o usuário entrar no site Regula Sun, clicar em Gráfico na barra de navegação superior, selecionar o ano de 2023, selecionar o indicador População Urbana e clicar no botão Gerar Gráfico o sistema deveria retornar um gráfico com o os dados de Campo Grande por padrão.

v 1.0.7 da aplicação, rodando no Google Chorme.

![Regula SUN-Google-Chrome-2023-05-30-14-34-29](https://github.com/PDS-1-P05/2023_1_front-end/assets/80921175/5dada063-9666-4b16-aaad-45d884a0895f)

**Comment by guilhermectprado** [comment]
Isso é erro de implementação que eu cometi kkkk, fiz com que  só executasse a geração do gráfico se todos os seletores tivessem alguma informação selecionada.
