### ISSUE TITLE
Gerar gráfico sem indicador selecionado

### ISSUE THREAD

**Issue by vitorhcassol** [PDS-1-P05/2023_1_front-end#55]
De acordo com o Caso de Teste 26 da H001, quando o usuário entrar no site Regula Sun, clicar em Gráfico na barra de navegação superior, selecionar o ano de 2023, selecionar o município de Campo Grande e clicar no botão Gerar Gráfico o sistema deveria retornar um gráfico com o os dados de Campo Grande e dos indicadores pré-selecionados pelo sistema.

v 1.0.7 da aplicação. navegador usado Google Chrome.

![Regula SUN-Google-Chrome-2023-05-30-14-54-17](https://github.com/PDS-1-P05/2023_1_front-end/assets/80921175/fe145d14-6487-4768-8e3e-0b15401b1490)

**Comment by guilhermectprado** [comment]
Isso é erro de implementação que eu cometi kkkk, fiz com que  só executasse a geração do gráfico se todos os seletores tivessem alguma informação selecionada.
