### ISSUE TITLE
Gerar gráfico sem ter selecionado qualquer município ou indicador

### ISSUE THREAD

**Issue by vitorhcassol** [PDS-1-P05/2023_1_front-end#56]
De acordo com o Caso de Teste 27 da H001, quando o usuário entrar no site Regula Sun, clicar em Gráfico na barra de navegação superior, selecionar o ano de 2023 e clicar no botão Gerar Gráfico o sistema deveria retornar um gráfico com os dados de Campo Grande e dos indicadores pré-selecionados pelo sistema.

v 1.0.7 da aplicação e navegador usado: Google Chorme.

![Regula SUN - Google Chrome 2023-05-30 15-00-59 (1)](https://github.com/PDS-1-P05/2023_1_front-end/assets/80921175/578d0ff0-5475-45d3-b445-be0e90fa311f)

**Comment by guilhermectprado** [comment]
Isso é erro de implementação que eu cometi kkkk, fiz com que  só executasse a geração do gráfico se todos os seletores tivessem alguma informação selecionada.
