### ISSUE TITLE
Medalhas do ranking tem o tamanho acompanhando o nome do município

### ISSUE THREAD

**Issue by vitorhcassol** [PDS-1-P05/2023_1_front-end#77]
Quando a API retorna o nome de um município muito grande para as 3 primeiras posições o design da página quebra pois a imagem das medalhas está acompanhando o tamanho do nome do município.

![image](https://github.com/PDS-1-P05/2023_1_front-end/assets/80921175/ecc520c9-0927-4f69-a314-01060eb7182d)

**Comment by guilhermectprado** [comment]
PR da issue aprovada, fechando issue.
