### ISSUE TITLE
O uso de vírgulas para separar casas decimais gera incoerência no salvamento dos dados

### ISSUE THREAD

**Issue by vitorhcassol** [PDS-1-P05/2023_1_front-end#82]
Quando importamos dados com números decimais tanto nas planilhas de indicadores quanto de metas, caso esses valores estejam no padrão brasileiro de separação de casas decimais que é através de vírgula, o banco acaba salvando esses valores como -1 já que o padrão dele é de usar ponto para a separação das casas decimais.

![WhatsApp Image 2023-06-20 at 16 41 08](https://github.com/PDS-1-P05/2023_1_front-end/assets/80921175/3db2c1da-d82e-486e-8b6f-a7dcbdd8f217)

![WhatsApp Image 2023-06-20 at 16 41 09](https://github.com/PDS-1-P05/2023_1_front-end/assets/80921175/fb51a541-17dd-4676-a56b-0f44f956d104)

**Comment by guilhermectprado** [comment]
PR aprovada, fechando issue
