### ISSUE TITLE
Notificação quando administrador insere arquivo csv errado

### ISSUE THREAD

**Issue by leticiayurie** [PDS-1-P05/2023_1_front-end#86]
Quando o usuário administrador está logado e insere um arquivo csv - seja ele indicador ou meta - que contém alguma coluna errada, o sistema envia uma mensagem de erro enorme. Pensando na UI/UX isso pode desagradar e confundir o usuário. @guilhermectprado , teria como ver esta questão, fazendo favor?

Segue o exemplo de como está agora:
![image](https://github.com/PDS-1-P05/2023_1_front-end/assets/88344321/32c41960-4ff3-458b-bab8-685ca4eb65ca)
![image](https://github.com/PDS-1-P05/2023_1_front-end/assets/88344321/389e52a6-e73a-4e7f-abc5-bf86ff3ee53c)

**Comment by guilhermectprado** [comment]
Vou melhorar e.e

**Comment by guilhermectprado** [comment]
PR aprovada, fechando issue.
