### ISSUE TITLE
Tamanho dos campos dos filtros do gráfico

### ISSUE THREAD

**Issue by leticiayurie** [PDS-1-P05/2023_1_front-end#87]
Os campos dos filtros do gráfico ocupam uma largura muito grande, tirando o foco principal da página: o gráfico. Deste modo, é importante apresentá-lo como visualização principal. Numa visão de Design UI/UX será melhor deixar estes campos menores e o gráfico com maior destaque assim que o usuário chega na página.

![image](https://github.com/PDS-1-P05/2023_1_front-end/assets/88344321/50233d13-3eea-4d7c-9fab-0bc1c9685de0)

**Comment by guilhermectprado** [comment]
PR aprovada, issue fechada.
